[Sim]
n_threads = 3 # number of parallel processes
n_clients = [9] # number of clients in federation
total_MC_it = 1 # number of Monte Carlo iterations

[Data]
val_size = 0 # size of validation set
partition_method = "homo" # {homo, hetero}
data_dir = "data/cifar10"
alpha_list = [0.1] # parameter for Latent Dirichlet Allocation
n_classes = 10 # number of classes in dataset

[ML]
method = "fedavg"        
lr = 0.05 # learning rate
momentum = 0.9 # momentum for SGD
wd = 0.001 # weight decay
communication_rounds = 10 # total number of comm rounds
epochs_list = [2] # number of local epochs
batch_size_list = [128] # batch size for local training