# Note that several of the parameters are given as lists to enable sweeping over parameters.

[Sim]
n_threads = 1
n_clients = 15
# 0: no defence (keep the malicous nodes), 1: oracle (remove all malicious nodes), 2: group testing 
MODE_list = [4] # 2  
# 0: permutation attack, 1: random labels, 2: 1->7 label flip
attack_list = [2]
total_MC_it = 10 # 10
n_malicious_list = [5] # 1, 3, 5, 2, 4, 
PCA_simulation = false

[PCA]
no_comp = 4

[Data]
val_size = 100
partition_method = "homo"  # homo, hetero
data_dir = "data/mnist"
alpha_list = [1e4]#
n_classes = 10

[ML]
method = "fedavg"  # fedavg, fedsgd
pretrained = 0
client_sample = 1.0
lr = 0.01
momentum = 0
wd = 0
communication_rounds = 10 #10000
epochs_list = [1]
batch_size_list = [64]

[GT]
n_tests = 8
group_test_round = 0#1 #1
test_threshold = 0.96 # GT threshold
crossover_probability_list = [0.05] #
manual_params = false
prevalence_list = [0.05] #
P_FA = 0.05
P_MD = 0.05
# Decoding thresholds
BCJR_min_threshold = 0.2
BCJR_max_threshold = 0.21
BCJR_step_threshold = 0.1
DELTA = -0.2

<<<<<<< HEAD
[QI]
threshold = 0
value = 'count'  # options: 'count', 'actual'
=======
[Test]
ss_thres = 0.6
>>>>>>> c0d2e46891478c737c83b0be2f0abce5fbd032e2

[Oracle]
kick_out_clients = false