# Note that several of the parameters are given as lists to enable sweeping over parameters.

[Sim]
n_threads = 2
n_clients = 15
# 0: No defence, 1: oracle, 2: FedGT - nm, 3: noiseless FedGT (not supported) 4:GM, 5:MKrum, 6: FedGT - Delta
MODE_list = [2] 
# 0: permutation attack, 1: random labels, 2: 1->7 label flip, 3:active attack (untargeted), 4: active attack (targeted)
n_malicious_list = [1, 2, 3, 4, 5] # 1,2,3,4,5
attack_list = [2]
total_MC_it = 3
QGT = true

[PCA]
no_comp = 4

[Data]
val_size = 100 # 100
partition_method = "homo"      # homo, hetero
data_dir = "data/fed_isic2019"
alpha_list = [1e4]
n_classes = 8

[ML]
method = "fedavg"         # fedavg
pretrained = 0
client_sample = 1.0
lr = 0.0005
momentum = 0.9
wd = 0.0001
communication_rounds = 40
epochs_list = [1]
batch_size_list = [64]

[GT]
n_tests = 8
group_test_round = 5
crossover_probability_list = [0.05] 
prevalence_list = [0.1]
P_FA = 0.05
P_MD = 0.05

[Test]
ss_thres = 0.0
beta = 0.5 # 0.25, 0.5, 0.75
