# Note that several of the parameters are given as lists to enable sweeping over parameters.

[Sim]
n_threads = 15 # 15
n_clients = 15 # 15
n_clients_total = 100

# 0: No defence, 
# 1: oracle, 
# 2: FedGT - nm, 
# 3: noiseless FedGT (not supported) 
# 4: GM, 
# 5: MKrum, 
# 6: FedGT - Delta
# 7: FedQGT
MODE_list = [7]   

# 0: permutation attack, 
# 1: random labels, 
# 2: 1->7 label flip, 
# 3: active data-poisoning attack (untargeted), 
# 4: active data-poisoning attack (targeted)
# 5: 
# 6: data-poison and model-poison attack (untargeted)
# 7: data-poison and model-poison attack (targeted)
attack_list = [3,6]

total_MC_it = 1
n_malicious_list =  [10,20,30]


[PCA]
no_comp = 4

[Data]
val_size = 100
partition_method = "homo"  # homo, hetero
data_dir = "data/cifar10"
alpha_list = [1e4] # 1e4:default [0.4, 0.6, 0.8, 1.0]
n_classes = 10

[ML]
method = "fedavg"  # fedavg
pretrained = 0
client_sample = 1.0
lr = 0.05
momentum = 0.9
wd = 0.001
communication_rounds = 30
epochs_list = [5] 
batch_size_list = [128]


[GT]
QGT = true
n_tests = 8 #12
group_test_round = 5
crossover_probability_list = [0.05]
prevalence_list = [0.2]
P_FA = 0.05
P_MD = 0.05

[Test]
ss_thres = 0.6
beta = 0.25 # 0.25, 0.5, 0.75