# Note that several of the parameters are given as lists to enable sweeping over parameters.
# Check the Loss!!!!!
[Sim]
n_threads = 2
n_clients = 15
# 0: no defence (keep the malicous nodes), 1: oracle (remove all malicious nodes), 2: group testing, 3: noiseless group testing, 4: GM_aggregation
MODE_list = [2] 
# 0: permutation attack, 1: random labels, 2: 1->7 label flip
n_malicious_list = [0]
attack_list = [2]
total_MC_it = 1
PCA_simulation = false

[PCA]
no_comp = 4

[Data]
val_size = 100 # 100
partition_method = "homo"      # homo, hetero
data_dir = "data/fed_isic2019"
alpha_list = [1e4]
n_classes = 8

[ML]
method = "fedavg"         # fedavg
pretrained = 0
client_sample = 1.0
lr = 0.0005
momentum = 0.9
wd = 0.0001
communication_rounds = 40#40
epochs_list = [1]
batch_size_list = [64]


[GT]
n_tests = 8#8                         #4#8,10
group_test_round = 5#5
test_threshold = 0.96               # GT threshold
crossover_probability_list = [0.05] #[0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45]
manual_params = false
prevalence_list = [0.1]
P_FA = 0.05
P_MD = 0.05
# Decoding thresholds
BCJR_min_threshold = 0.2
BCJR_max_threshold = 0.21
BCJR_step_threshold = 0.1
DELTA = -0.2

[Test]
ss_thres = 0.6

[Oracle]
kick_out_clients = false
which_ones = []
