# Note that several of the parameters are given as lists to enable sweeping over parameters.

[Sim]
n_threads = 8
n_clients = 15
# 0: no defence (keep the malicous nodes), 1: oracle (remove all malicious nodes), 2: group testing 
MODE_list = [0,1,2,3]  
# 0: permutation attack, 1: random labels, 2: 1->7 label flip
attack_list = [0]
total_MC_it = 5
n_malicious_list = [3]

[Data]
val_size = 100
partition_method = "homo"  # homo, hetero
data_dir = "data/cifar10"
alpha_list = [1e4] 
n_classes = 10

[ML]
method = "fedavg"  # fedavg
pretrained = 0
client_sample = 1.0
lr = 0.05
momentum = 0.9
wd = 0.001
communication_rounds = 40
epochs_list = [5]
batch_size_list = [128]


[GT]
n_tests = 8
group_test_round = 5
test_threshold = 0.96 # GT threshold
crossover_probability_list = [0.05]
prevalence_list = [0.2]
P_FA = 0.05
P_MD = 0.05
manual_params = false
# Decoding thresholds
BCJR_min_threshold = 0.1
BCJR_max_threshold = 0.905
BCJR_step_threshold = 0.1






    
    
    